[workspace]
resolver = "2"
members = [
    "crates/rylus-core",
    "crates/rylus-ffi",
    "crates/rylus-capture",
    "crates/rylus-encode",
    "crates/rylus-input",
    "crates/rylus-transport",
    "crates/rylus-gui",
    "crates/rylus-server",
]

[workspace.package]
version = "0.13.0"
authors = ["HMH <henry@freedesk.net>"]
edition = "2021"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
# Internal crates
rylus-core = { path = "crates/rylus-core" }
rylus-ffi = { path = "crates/rylus-ffi" }
rylus-capture = { path = "crates/rylus-capture" }
rylus-encode = { path = "crates/rylus-encode" }
rylus-input = { path = "crates/rylus-input" }
rylus-transport = { path = "crates/rylus-transport" }
rylus-gui = { path = "crates/rylus-gui" }

# External dependencies
bitflags = { version = "^2.6", features = ["serde"] }
clap = { version = "4.5.18", features = ["derive"] }
clap_complete = "4.5.29"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
tokio = { version = "^1", features = ["fs", "macros", "rt-multi-thread", "sync", "net", "time"] }
tracing = "^0.1"
tracing-subscriber = { version = "^0.3", features = ["ansi", "json"], default-features = false }

[profile.release]
lto = true
opt-level = 3
