[package]
name = "rylus-capture"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Screen capture backends for Rylus"

[features]
default = []
x11 = ["dep:rylus-ffi"]

[dependencies]
rylus-core = { workspace = true }
rylus-ffi = { workspace = true, features = ["x11"], optional = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
dbus = "^0.9"
rand = "0.9"
gstreamer = "^0.24"
gstreamer-app = { version = "^0.24", features = ["v1_16"] }
gstreamer-video = "^0.24"

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "^0.10"
core-graphics = "^0.24"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["d3d11", "d3dcommon", "dxgi", "dxgi1_2", "dxgitype"] }
wio = "0.2.2"
captrs = "^0.3.1"
