[package]
name = "rylus-gui"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "egui GUI for Rylus"

[dependencies]
rylus-core = { workspace = true, features = ["gui"] }
eframe = "0.31"
parking_lot = { workspace = true }
egui = "0.31"
egui_extras = { version = "0.31", features = ["image"] }
image = { version = "^0.25", features = ["png"], default-features = false }
percent-encoding = "2.3"
qrcode = "0.14.1"
tracing = { workspace = true }

[target.'cfg(not(target_os = "windows"))'.dependencies]
pnet_datalink = "^0.35"
