[package]
name = "rylus-transport"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Transport layer (WebSocket) for Rylus"

[dependencies]
rylus-core = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = "0.3"
hyper = { version = "^1.4", features = ["server", "http1", "http2"] }
hyper-util = { version = "0.1.20", features = ["tokio"] }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
