[package]
name = "rylus-encode"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Video encoding for Rylus"

[[bin]]
name = "bench"
path = "src/bin/bench.rs"

[dependencies]
rylus-core = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dependencies.ffmpeg-sys-next]
version = "8"
default-features = false
features = ["avcodec", "avformat", "avfilter", "swscale", "swresample"]
